import NavBar from "@/components/NavBar";
import Dashboard from "@/components/Dashboard";
import Styles from "../styles/styles.module.scss";
import { Html } from "next/document";

export const metadata = {
  title: "Star Wars Universe",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Styles.body}>
        <div className={Styles.container}>
          <NavBar />
          <Dashboard>{children}</Dashboard>
        </div>
      </body>
    </html>
  );
}
